#!/usr/bin/env bash
sudo pacman -S --needed --noconfirm gdm gnome-themes-extra gvfs-google gvfs-mtp alacritty nvim zsh git timeshift switcheroo-control gnome-control-center fwupd nvidia-open gnome-backgrounds flatpak gnome-software noto-fonts noto-fonts-emoji noto-fonts-cjk ttf-liberation ttf-jetbrains-mono-nerd gnome-shell-extension-appindicator
flatpak install -y org.mozilla.firefox com.mattjakeman.ExtensionManager
sudo systemctl enable gdm bluetooth switcheroo-control

sudo pacman -S --needed --noconfirm hyprland hyprpaper hypridle hyprlock xdg-desktop-portal-hyprland polkit-gnome waybar rofi-wayland rofimoji wtype grim slurp cliphist pavucontrol brightnessctl xorg-xhost
echo "removing config"
rm -rf ~/.config/alacritty
rm -rf ~/.config/hypr
rm -rf ~/.config/rofi
rm -rf ~/.config/waybar
echo "copying config"
cp -r dotfiles/.config/alacritty ~/.config
cp -r dotfiles/.config/hypr ~/.config
cp -r dotfiles/.config/rofi ~/.config
cp -r dotfiles/.config/waybar ~/.config
hyprctl reload
killall waybar
hyprctl dispatch exec waybar

gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-dark"

echo "done"
