#!/usr/bin/env bash
sudo pacman -S --needed --noconfirm - < packages
sudo pacman -S --needed --noconfirm hyprland-packages
xargs flatpak install -y < flatpaks
xargs sudo systemctl enable < services

echo "removing config"
rm -rf ~/.config/ghostty
rm -rf ~/.config/hypr
rm -rf ~/.config/rofi
rm -rf ~/.config/waybar
echo "copying config"
cp -r dotfiles/.config/ghostty ~/.config
cp -r dotfiles/.config/hypr ~/.config
cp -r dotfiles/.config/rofi ~/.config
cp -r dotfiles/.config/waybar ~/.config
hyprctl reload
killall waybar
hyprctl dispatch exec waybar

gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-dark"

echo "done"
