general.import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
opacity = 0.7
padding = { x = 15, y = 15 }

[font]
size = 12.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"
